server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moe_inve?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm

mybatis:
  typeAliasesPackage: com.sa.entity
  mapperLocations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml
  path: log

sa:
  shiro:
    redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
