server:
  port: 8080

  tomcat:
    uri-encoding: UTF-8

#开启GZIP
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html,text/plain,text/css
    min-response-size: 2048

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/server_admin?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#格式化日期
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm

  mvc:
    favicon:
      enabled: false

mybatis:
  typeAliasesPackage: com.sa.entity
  mapperLocations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml
  path: log
